export enum Event {
  connection = "connection",
  changeConfig = "changeConfig",
  getRoom = "getRoom",
  getReady = "getReady",
  countdownStart = 'countdownStart',
  countdownStop = 'countdownStop',
  startGame = "startGame",
  leaveRoom = "leaveRoom",
  shopStart = "shopStart",
  shopEnd = "shopEnd",
  bid = "bid",
  pickStart = "pickStart",
  pickEnd = "pickEnd",
  pick = "pick",
  turnStart = "turnStart",
  turnEnd = "turnEnd",
  getSelf = "getSelf",
  getShop = "getShop",
  error = "error"
}